### ISSUE TITLE
Chub/Characterhub v2 cards fail.

### ISSUE THREAD

**Issue by thijsi123** [Barafu/tavern_card_tools#1]
Random character I tried (Has a lorebook)
https://characterhub.org/characters/Lightguard/lancer-f797e4bb98a6
Asterisks were not removed.

G:\Downloads\tavern_card_tools>tavern_card_tools.exe de8 --path "main_lancer-f797e4bb98a6_spec_v2.
png"
tavern card tools v0.1.2
Deasterisk file: main_lancer-f797e4bb98a6_spec_v2.png
Character name is Scáthach
Output file name: de8.main_lancer-f797e4bb98a6_spec_v2.png
Done

G:\Downloads\tavern_card_tools>

INPUT

![main_lancer-f797e4bb98a6_spec_v2](https://github.com/user-attachments/assets/1ca30aba-73f5-4677-9afe-2a53e0f8bbed)

OUTPUT

![de8 main_lancer-f797e4bb98a6_spec_v2](https://github.com/user-attachments/assets/e3f26c26-6321-4324-b84b-77e87d2901c9)

**Comment by thijsi123** [comment]
Just tried tavern card tools v0.1.3 and it seems to work now. : )

**Comment by Barafu** [comment]
Thanks for report, but looks I already fixed it in v0.1.3. Would you mind checking again on your side? 

I looked into the card manually: it does have an alternative greeting... Which is empty. So whoever messed it up, wasn't me. The lorebook seems to be asterisk-free.

**Comment by thijsi123** [comment]
Tried; https://chub.ai/characters/Sugondees/mona-25f32cc4d430 (nsfw image)
(knowing that it has multiple greetings). All Alt. Greetings are there, all asterisks have been removed correctly!
